pool:
  vmImage: 'Ubuntu 18.04'

trigger:
- none

resources:
- repo: self

variables:
  azureServiceConnection: 'SP.dmappsdevacr'
  imageRepository: 'dmapps_img'
  tag: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(azureServiceConnection)

    - task: Docker@2
      displayName: Build and push image to Azure container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/dockerfile'
        containerRegistry: $(azureServiceConnection)
        tags: |
          latest
          $(tag)
          $(productionTag)

    - task: Docker@2
      displayName: Logout from ACR
      inputs:
       command: logout
       containerRegistry: $(azureServiceConnection)
