pool: dmapps

trigger:
  - none

steps:
  - script: |
      # install pre-requisites
      whoami
      python3.8 -V
      python3.8 -m pip install --upgrade pip setuptools wheel
      python3.8 -m pip install -r requirements.txt
      mkdir media
      mkdir media/travel
      mkdir media/travel/temp
      mkdir media/projects
      mkdir media/projects/temp
      mkdir media/inventory
      mkdir media/inventory/temp
      mkdir media/ihub
      mkdir media/ihub/temp
      python3.8 manage.py collectstatic --no-input
      # python3.8 manage.py migrate
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Install Prerequisites and Run Local Migrations '

  - script: |
      python3.8 manage.py test -b  shared_models.test
    condition: succeededOrFailed()
    displayName: 'Tests for shared models'

  - script: |
      mkdir ./media
      mkdir ./media/projects
      mkdir ./media/projects/temp
      python3.8 manage.py test -b projects2.test
    condition: succeededOrFailed()
    displayName: 'Tests for projects (v2)'

  - script: |
      python3.8 manage.py test -b travel.test
    condition: succeededOrFailed()
    displayName: 'Tests for travel'

  - script: |
      python3.8 manage.py test -b whalesdb.test
    condition: succeededOrFailed()
    displayName: 'Tests for whalesdb'

  - script: |
      python3.8 manage.py test -b inventory.test
    condition: succeededOrFailed()
    displayName: 'Tests for inventory'

  - script: |
      python3.8 manage.py test -b shiny.test
    condition: succeededOrFailed()
    displayName: 'Tests for shiny'

  - script: |
      python3.8 manage.py test -b ihub.test
    condition: succeededOrFailed()
    displayName: 'Tests for ihub'

  - script: |
      python3.8 manage.py test -b csas.test
    condition: succeededOrFailed()
    displayName: 'Tests for csas'

  - script: |
      python3.8 manage.py test -b cruises.test
    condition: succeededOrFailed()
    displayName: 'Tests for cruises'

  - script: |
      python3.8 manage.py test -b whalebrary.test
    condition: succeededOrFailed()
    displayName: 'Tests for whalebrary'

  - script: |
      python3.8 manage.py test --exclude-tag=Functional -b bio_diversity.test
    condition: succeededOrFailed()
    displayName: 'Tests for biodiversity'
