# Generated by Django 2.2.13 on 2020-09-02 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analyses',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, verbose_name='ISO3166-2 country code')),
                ('country_name', models.CharField(max_length=120, verbose_name='Country name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='MarineRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'marine region',
                'verbose_name_plural': 'marine regions',
            },
        ),
        migrations.CreateModel(
            name='Preservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'preservation',
                'verbose_name_plural': 'preservations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pi', models.CharField(max_length=100, verbose_name='Principal investigator')),
                ('description', models.TextField(blank=True, null=True)),
                ('marine_region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.MarineRegion', verbose_name='Marine Region Name')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'sample type',
                'verbose_name_plural': 'sample types',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('container', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'storage type',
                'verbose_name_plural': 'storage types',
            },
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subregion', models.CharField(max_length=100, verbose_name='ISO3316 subregion name')),
                ('code', models.CharField(max_length=10, verbose_name='ISO3316 subregion code')),
            ],
            options={
                'verbose_name': 'subregion',
                'verbose_name_plural': 'subregions',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datetime (UTC)')),
                ('start_depth', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Start Depth (m)')),
                ('end_depth', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='End Depth (m)')),
                ('sounding', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Sounding (m)')),
                ('ancillary_data', models.BooleanField(default=False, verbose_name='Ancillary Data?')),
                ('sample_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sample ID')),
                ('core', models.CharField(blank=True, max_length=128, null=True, verbose_name='Core ID')),
                ('filter', models.CharField(blank=True, max_length=128, null=True, verbose_name='Filter ID')),
                ('filter_spm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Filter Suspended Particulate Matter (SPM, g/m^3)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Sample Comments')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Analysis', verbose_name='Sample analysis method')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Collection', verbose_name='Sample collection method')),
                ('preservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Preservation', verbose_name='Sample preservation method')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Project')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.SampleType', verbose_name='Sample type')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.StorageType', verbose_name='Sample storage method')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Unit', verbose_name='Sample units')),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'samples',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.CharField(max_length=5, verbose_name='Diameter')),
                ('value', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Sample fraction')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grainsize.Sample', verbose_name='Sample')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
            },
        ),
    ]
