# Generated by Django 2.2.2 on 2019-06-11 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Branch', verbose_name='branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeClassesLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionEmploymentEquityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionLinguisticRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionStaffingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionTenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Division', verbose_name='division')),
            ],
            options={
                'ordering': ['division', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='short name for planned staffing (<255 characters)')),
                ('position_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='position number')),
                ('position_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='position title')),
                ('is_key_position', models.BooleanField(default=False, verbose_name='is key position')),
                ('employee_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='employee last name')),
                ('employee_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='employee first name')),
                ('estimated_start_date', models.DateField(blank=True, null=True, verbose_name='start date (estimated)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date (actual)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date (actual)')),
                ('duration_temporary_coverage', models.IntegerField(blank=True, null=True, verbose_name='duration of temporary coverage based on end date (months)')),
                ('potential_rollover_date', models.DateField(blank=True, null=True, verbose_name='potential rollover date based on start date')),
                ('allocation', models.FloatField(blank=True, null=True, verbose_name='allocation (0 - 1.00)')),
                ('rd_approval_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='RDS approval number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Staffing Request Notes')),
                ('date_last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date last modified')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.FiscalYear', verbose_name='fiscal year')),
                ('funding_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.FundingType', verbose_name='funding type')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('position_employment_equity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.PositionEmploymentEquityRequirement', verbose_name='employment equity requirement')),
                ('position_linguistic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.PositionLinguisticRequirement', verbose_name='linguistic requirement')),
                ('position_security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.PositionSecurity', verbose_name='position security requirement')),
                ('position_staffing_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.PositionStaffingOption', verbose_name='position staffing option')),
                ('position_tenure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.PositionTenure', verbose_name='position tenure')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports_to_manager', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('responsibility_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.ResponsibilityCenter', verbose_name='responsibility center (if known)')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Section', verbose_name='section')),
            ],
            options={
                'ordering': ['fiscal_year__name', 'responsibility_center__name', 'position_number', 'position_title'],
            },
        ),
        migrations.CreateModel(
            name='StaffingPlanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffingPlanFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_coding', models.CharField(blank=True, max_length=255, null=True, verbose_name='financial coding')),
                ('funding_amount', models.FloatField(verbose_name='funding amount ($)')),
                ('staffing_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.StaffingPlan', verbose_name='staffing_plan')),
            ],
            options={
                'ordering': ['staffing_plan', 'financial_coding', 'funding_amount'],
            },
        ),
        migrations.AddField(
            model_name='staffingplan',
            name='staffing_plan_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.StaffingPlanStatus', verbose_name='staffing plan status'),
        ),
        migrations.AddField(
            model_name='staffingplan',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.WorkLocation', verbose_name='work location'),
        ),
        migrations.CreateModel(
            name='EmployeeClassesLevelsPayRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_increment', models.IntegerField(blank=True, null=True, verbose_name='Pay Increment')),
                ('pay_amount', models.FloatField(blank=True, null=True, verbose_name='Annual Pay')),
                ('employee_class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.EmployeeClassesLevel', verbose_name='employee class and level')),
            ],
            options={
                'ordering': ['employee_class_level', 'pay_increment'],
            },
        ),
    ]
