# Generated by Django 2.2.2 on 2019-06-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='responsibilitycenter',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='section',
            name='division',
        ),
        migrations.AlterField(
            model_name='staffingplan',
            name='responsibility_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.ResponsibilityCenter', verbose_name='responsibility center (if known)'),
        ),
        migrations.AlterField(
            model_name='staffingplan',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Section', verbose_name='section'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='ResponsibilityCenter',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
