# Generated by Django 2.2.2 on 2019-06-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190611_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingplan',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.FiscalYear', verbose_name='fiscal year'),
        ),
        migrations.AlterField(
            model_name='staffingplan',
            name='funding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.FundingSource', verbose_name='funding type'),
        ),
        migrations.DeleteModel(
            name='FiscalYear',
        ),
    ]
