# Generated by Django 2.2.2 on 2019-06-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190613_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingplan',
            name='employee_class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.EmployeeClassesLevel', verbose_name='employee class and level'),
        ),
    ]
