# Generated by Django 2.2.2 on 2019-06-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffingplan_employee_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingplanfunding',
            name='staffing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_funding', to='staff.StaffingPlan', verbose_name='staffing_plan'),
        ),
    ]
