# Generated by Django 2.2.2 on 2020-02-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necropsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=250, verbose_name='Unique ID')),
                ('item_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Item')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('owner', models.CharField(blank=True, max_length=250, null=True, verbose_name='Owner')),
                ('size', models.CharField(blank=True, max_length=250, null=True, verbose_name='Size (if applicable)')),
                ('container_space', models.IntegerField(blank=True, null=True, verbose_name='Container Space Available (if applicable)')),
                ('category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Category')),
                ('type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('lent_to', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('lent_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('quantity_oh', models.IntegerField(blank=True, null=True)),
                ('quantity_oo', models.IntegerField(blank=True, null=True)),
                ('last_audited', models.DateTimeField(blank=True, null=True)),
                ('last_audited_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('location_stored', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('bin_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('items_quantity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='necropsy.Items', verbose_name='items')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('contact_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('last_invoice', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('last_purchased', models.DateTimeField(blank=True, null=True)),
                ('last_purchased_by', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Certainty',
        ),
        migrations.RemoveField(
            model_name='fieldname',
            name='used_for',
        ),
        migrations.DeleteModel(
            name='HealthStatus',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='LifeStage',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='life_stage',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='original_mediafile',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='mediafilesighting',
            name='species',
        ),
        migrations.AlterUniqueTogether(
            name='metadatafieldcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadatafieldcategory',
            name='metadata_field',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='outing',
        ),
        migrations.RemoveField(
            model_name='observationmetadatum',
            name='metadata_field',
        ),
        migrations.RemoveField(
            model_name='observationmetadatum',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observationplatform',
            name='observation_platform_type',
        ),
        migrations.DeleteModel(
            name='ObservationPlatformType',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='certainty',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='life_stage',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='observationsighting',
            name='species',
        ),
        migrations.RemoveField(
            model_name='originalmediafile',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='originalmediafile',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='originalmediafilemetadatum',
            name='metadata_field',
        ),
        migrations.RemoveField(
            model_name='originalmediafilemetadatum',
            name='original_mediafile',
        ),
        migrations.RemoveField(
            model_name='outing',
            name='observation_platform',
        ),
        migrations.RemoveField(
            model_name='processedmediafile',
            name='analyst',
        ),
        migrations.RemoveField(
            model_name='processedmediafile',
            name='original_mediafile',
        ),
        migrations.RemoveField(
            model_name='processedmediafile',
            name='species',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='necropsy.Role', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='FieldName',
        ),
        migrations.DeleteModel(
            name='MediafileSighting',
        ),
        migrations.DeleteModel(
            name='MetadataFieldCategory',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='ObservationMetadatum',
        ),
        migrations.DeleteModel(
            name='ObservationPlatform',
        ),
        migrations.DeleteModel(
            name='ObservationSighting',
        ),
        migrations.DeleteModel(
            name='OriginalMediafile',
        ),
        migrations.DeleteModel(
            name='OriginalMediafileMetadatum',
        ),
        migrations.DeleteModel(
            name='Outing',
        ),
        migrations.DeleteModel(
            name='ProcessedMediafile',
        ),
        migrations.AddField(
            model_name='lending',
            name='quantity_unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='necropsy.Quantity', verbose_name='items'),
        ),
    ]
