# Generated by Django 3.1.6 on 2021-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metmeeting',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='request', to='csas.ReqRequest', verbose_name='Request'),
        ),
    ]
