# Generated by Django 3.1.6 on 2021-04-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0002_metmeeting_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubpublication',
            name='lead_author_2',
            field=models.TextField(blank=True, null=True, verbose_name='Lead Author'),
        ),
        migrations.AddField(
            model_name='pubpublication',
            name='other_author_2',
            field=models.TextField(blank=True, null=True, verbose_name='Other Author(s)'),
        ),
        migrations.AlterField(
            model_name='metmeeting',
            name='request',
            field=models.ManyToManyField(blank=True, related_name='req_meeting', to='csas.ReqRequest', verbose_name='Request'),
        ),
    ]
