# Generated by Django 3.1.6 on 2021-04-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0003_auto_20210404_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubpublication',
            name='lead_author_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead Author'),
        ),
        migrations.AlterField(
            model_name='pubpublication',
            name='other_author_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Author(s)'),
        ),
    ]
