# Generated by Django 3.1.6 on 2021-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_auto_20210225_1538'),
        ('csas', '0004_auto_20210404_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubpublication',
            name='lead_region',
        ),
        migrations.AddField(
            model_name='pubpublication',
            name='lead_region',
            field=models.ManyToManyField(blank=True, to='shared_models.Region', verbose_name='Lead Region'),
        ),
    ]
