# Generated by Django 3.2 on 2021-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csas', '0005_auto_20210405_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubpublication',
            name='meeting',
            field=models.ManyToManyField(blank=True, related_name='met_publication', to='csas.MetMeeting', verbose_name='Meeting'),
        ),
    ]
