# Generated by Django 2.2.2 on 2020-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200520_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_at_risk',
            field=models.BooleanField(default=False, verbose_name='Is your dataset at risk?'),
        ),
    ]
