# Generated by Django 2.2.2 on 2020-01-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceanography', '0002_auto_20190326_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('eng_text', models.TextField(verbose_name='English text')),
                ('fra_text', models.TextField(blank=True, null=True, verbose_name='French text')),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
    ]
