# Generated by Django 3.1.2 on 2021-01-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0033_auto_20210107_1206'),
        ('publications', '0004_auto_20191004_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='division',
        ),
        migrations.AddField(
            model_name='project',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.division', verbose_name='Division'),
        ),
    ]
