# Generated by Django 2.2.2 on 2020-02-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumenttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='vault.InstrumentType', verbose_name='Type of instrument'),
        ),
    ]
