# Generated by Django 2.2.2 on 2020-02-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20200212_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumenttype',
            options={},
        ),
    ]
