# Generated by Django 2.2.2 on 2020-02-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_auto_20200212_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldName',
        ),
    ]
