# Generated by Django 2.2.2 on 2020-02-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_delete_fieldname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='')),
                ('used_for', models.ManyToManyField(blank=True, to='vault.Instrument', verbose_name='')),
            ],
        ),
    ]
