# Generated by Django 2.2.2 on 2020-02-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_fieldname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_type',
        ),
    ]
