# Generated by Django 2.2.2 on 2020-02-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_remove_instrument_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruments', to='vault.InstrumentType', verbose_name='Type of instrument'),
            preserve_default=False,
        ),
    ]
