# Generated by Django 2.2.2 on 2020-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0025_region_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='Country_of_origin',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='ICES_SHIPC_ship_codes',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='Platform_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='Platform_type',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
