# Generated by Django 2.2.2 on 2020-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0026_auto_20200110_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='West_bound_decimal_degrees_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
