# Generated by Django 2.2.2 on 2020-01-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0027_cruise_west_bound_decimal_degrees_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='West_bound_decimal_degrees_longitude',
        ),
        migrations.AddField(
            model_name='cruise',
            name='East_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Easternmost longitude of the sampling (decimal degrees, negative for Western Hemisphere longitude)'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='Funding_agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding agency of the data collection'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='Funding_project_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The ID of your funded project'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='Funding_project_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The title of your funded project'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='North_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Northernmost latitude of the sampling (decimal degrees, negative for Southern Hemisphere latitude)'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='References',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provide the bibliographic citations for publications describing the data set. Example: cruise report, scientific paper'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='Research_Projects_Program',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The collaborative research or programs which the cruise is part of, separate them with comma'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='South_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Southernmost latitude of the sampling (decimal degrees, negative for Southern Hemisphere latitude)'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='West_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Westernmost longitude of the sampling (decimal degrees, negative for Western Hemisphere longitude)'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The intentions of the cruise'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='A narrative summary of the cruise'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_name',
            field=models.CharField(max_length=255, verbose_name='Provide a descriptive title'),
        ),
    ]
