# Generated by Django 2.2.2 on 2020-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0028_auto_20200115_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='East_bound_longitude',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='North_bound_latitude',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='Research_Projects_Program',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='South_bound_latitude',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='West_bound_longitude',
        ),
        migrations.AddField(
            model_name='cruise',
            name='East_bound_longitude_decimal_deg_neg_W',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='North_bound_latitude_decimal_deg_neg_S',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='Research_Projects_Programs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='South_bound_latitude_decimal_deg_neg_S',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cruise',
            name='West_bound_longitude_decimal_deg_neg_W',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='Address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='Region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_project_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='References',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
