# Generated by Django 2.2.2 on 2020-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0029_auto_20200116_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruise',
            name='mission_name',
            field=models.CharField(max_length=255, verbose_name='Provide a descriptive title'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_number',
            field=models.CharField(max_length=255, verbose_name='numero de mission'),
        ),
    ]
