# Generated by Django 2.2.2 on 2020-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0031_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='IMO_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
