# Generated by Django 2.2.2 on 2020-01-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0032_vessel_imo_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpText',
        ),
    ]
