# Generated by Django 2.2.2 on 2020-01-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0033_delete_helptext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='East_bound_longitude_decimal_deg_neg_W',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='North_bound_latitude_decimal_deg_neg_S',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='South_bound_latitude_decimal_deg_neg_S',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='West_bound_longitude_decimal_deg_neg_W',
        ),
        migrations.AddField(
            model_name='cruise',
            name='East_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='East Bound Longitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='North_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='North Bound Latitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='South_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='South Bound Latitude'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='West_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='West Bound Longitude'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Agency Name'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_project_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Project ID'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Funding_project_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Funding Project Title'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='References',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='Research_Projects_Programs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Research Projects Programs'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='area_of_operation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area of Operation'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='chief_scientist',
            field=models.CharField(max_length=255, verbose_name='Chief Scientist'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_name',
            field=models.CharField(max_length=255, verbose_name='Mission Name'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='mission_number',
            field=models.CharField(max_length=255, verbose_name='Mission Number'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='number_of_profiles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Profiles'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='samplers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Samplers'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
