# Generated by Django 2.2.2 on 2020-01-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0034_auto_20200122_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variable_name', models.CharField(max_length=255)),
                ('Variable_abbreviation_in_files', models.CharField(blank=True, max_length=255, null=True)),
                ('Variable_unit', models.CharField(max_length=255)),
                ('Observation_type', models.CharField(max_length=255, verbose_name='Observation Type')),
                ('Measured_or_calculated', models.CharField(blank=True, max_length=255, null=True)),
                ('Calculation_method', models.CharField(blank=True, max_length=255, null=True)),
                ('Sampling_instrument', models.CharField(max_length=255)),
                ('Analysing_instrument', models.CharField(blank=True, max_length=255, null=True)),
                ('Detailed_sampling_analyzing_information', models.CharField(blank=True, max_length=255, null=True)),
                ('Calibration_information', models.CharField(blank=True, max_length=255, null=True)),
                ('Method_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('Analst_sampler', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['Variable_name'],
            },
        ),
        migrations.AddField(
            model_name='cruise',
            name='Observations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.Observations'),
        ),
    ]
