# Generated by Django 2.2.2 on 2019-06-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_auto_20190604_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='app',
            field=models.CharField(blank=True, choices=[('general', 'n/a'), ('esee', 'ESEE (not part of site)'), ('plankton', 'Plankton Net (not part of site)'), ('projects', 'Science project planning'), ('staff', 'Staff Planning Tool'), ('tickets', 'Data Management Tickets')], default='general', max_length=25, null=True, verbose_name='application name'),
        ),
    ]
